version: "3"
services:
  front:
    image: node:14
    container_name: node_sass
    volumes:
      - ./www/public:/var/www/html/public/
      - ./www/package.json:/var/www/html/package.json
    working_dir: /var/www/html/
    command:
      - /bin/sh
      - '-c'
      - 'npm install && npm run sass'

  back:
    build: site
    container_name: docker-back
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html/
      - ./server/000-default.conf:/etc/apache2/sites-available/000-default.conf
      - ./server/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - database


  database:
    image: mysql:5.7
    container_name: database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PWD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PWD}
    volumes:
      - ./db_data:/var/lib/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: myadmin
    depends_on:
      - database
    ports:
      - 8888:80
    environment:
      - PMA_ARBITRARY=1

  redis:
    image: library/redis:6.2.4-alpine
    container_name: redis

  elasticsearch:
    image: library/elasticsearch:7.13.3
    container_name: elasticsearch
    environment:
      - "discovery.type=single-node"
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: library/logstash:7.13.3
    container_name: logstash
    ports:
      - "9600:9600"
    volumes:
      - .\logstash:/usr/share/logstash/pipeline
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: library/kibana:7.13.3
    container_name: kibana
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    networks:
      - elk

  smtp:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

networks:
  elk:
    driver: bridge

volumes:
  esdata:
    driver: local